[package]

name = "nickel_postgres"
version = "0.1.0"
authors = [
    "bguiz",
    "Matthew Bentley <matthew@bentley.link>"
]

[dependencies]
postgres = "^0.11"
r2d2 = "^0.6"
r2d2_postgres = "^0.10"
plugin = "^0.2"
typemap = "^0.3"
nickel = "^0.7"
